// Kamus kata kunci umum (Bahasa Indonesia, Inggris, gaul/slang) -> kategori internal etalase.
// Ini membantu pencarian mencocokkan niat pengunjung ke kategori yang tepat secara cerdas.
export const CATEGORY_SYNONYMS: Record<string, string> = {
  // === FASHION & OOTD ===
  baju: "fashion",
  pakaian: "fashion",
  outfit: "fashion",
  ootd: "fashion",
  busana: "fashion",
  sandang: "fashion",
  style: "fashion",
  gaya: "fashion",
  atasan: "fashion",
  bawahan: "fashion",
  kemeja: "fashion",
  kaos: "fashion",
  tshirt: "fashion",
  t_shirt: "fashion",
  kaos_oblong: "fashion",
  polo: "fashion",
  blouse: "fashion",
  tunik: "fashion",
  dress: "fashion",
  gaun: "fashion",
  rok: "fashion",
  celana: "fashion",
  jeans: "fashion",
  denim: "fashion",
  kulot: "fashion",
  chinos: "fashion",
  cargo: "fashion",
  jaket: "fashion",
  jacket: "fashion",
  sweater: "fashion",
  hoodie: "fashion",
  outer: "fashion",
  cardigan: "fashion",
  rompi: "fashion",
  vest: "fashion",
  jas: "fashion",
  blazer: "fashion",
  sepatu: "fashion",
  shoes: "fashion",
  sneakers: "fashion",
  sandal: "fashion",
  sandals: "fashion",
  selop: "fashion",
  topi: "fashion",
  hat: "fashion",
  cap: "fashion",
  kupluk: "fashion",
  tas: "fashion",
  bag: "fashion",
  handbag: "fashion",
  dompet: "fashion",
  wallet: "fashion",
  ikat_pinggang: "fashion",
  sabuk: "fashion",
  belt: "fashion",
  kaos_kaki: "fashion",
  socks: "fashion",
  kacamata: "fashion",
  glasses: "fashion",
  sunglasses: "fashion",
  aksesoris_fashion: "fashion",
  kalung: "fashion",
  gelang: "fashion",
  cincin: "fashion",
  anting: "fashion",
  hijab: "fashion",
  jilbab: "fashion",
  kerudung: "fashion",
  pashmina: "fashion",
  scarp: "fashion",

  // === SKINCARE, BEAUTY & PERSONAL CARE ===
  skincare: "skincare",
  skin_care: "skincare",
  perawatan: "skincare",
  kosmetik: "skincare",
  makeup: "skincare",
  make_up: "skincare",
  dandan: "skincare",
  cantik: "skincare",
  glowing: "skincare",
  wajah: "skincare",
  muka: "skincare",
  kulit: "skincare",
  serum: "skincare",
  toner: "skincare",
  moisturizer: "skincare",
  pelembab: "skincare",
  sunscreen: "skincare",
  tabir_surya: "skincare",
  sunblock: "skincare",
  facial_wash: "skincare",
  sabun_muka: "skincare",
  cleanser: "skincare",
  micellar_water: "skincare",
  masker_wajah: "skincare",
  mask: "skincare",
  clay_mask: "skincare",
  sheet_mask: "skincare",
  exfoliator: "skincare",
  scrub: "skincare",
  acne: "skincare",
  jerawat: "skincare",
  obat_jerawat: "skincare",
  cream: "skincare",
  krim: "skincare",
  gel: "skincare",
  lipbalm: "skincare",
  lip_balm: "skincare",
  liptint: "skincare",
  lip_tint: "skincare",
  lipcream: "skincare",
  lip_cream: "skincare",
  lipstick: "skincare",
  gincu: "skincare",
  eyeliner: "skincare",
  maskara: "skincare",
  mascara: "skincare",
  eyeshadow: "skincare",
  bedak: "skincare",
  powder: "skincare",
  cushion: "skincare",
  foundation: "skincare",
  concealer: "skincare",
  blush: "skincare",
  body_lotion: "skincare",
  hand_body: "skincare",
  lotion: "skincare",
  parfum: "skincare",
  perfume: "skincare",
  pewangi: "skincare",
  cologne: "skincare",
  shampoo: "skincare",
  sampo: "skincare",
  conditioner: "skincare",
  sabun: "skincare",
  soap: "skincare",
  deodorant: "skincare",
  body_wash: "skincare",

  // === GADGET, TECH & ACCESSORIES ===
  gadget: "gadget",
  gajet: "gadget",
  hp: "gadget",
  handphone: "gadget",
  ponsel: "gadget",
  smartphone: "gadget",
  telepon: "gadget",
  android: "gadget",
  iphone: "gadget",
  ios: "gadget",
  tablet: "gadget",
  ipad: "gadget",
  laptop: "gadget",
  komputer: "gadget",
  pc: "gadget",
  computer: "gadget",
  mouse: "gadget",
  keyboard: "gadget",
  tws: "gadget",
  earbuds: "gadget",
  earphone: "gadget",
  headphone: "gadget",
  headphones: "gadget",
  headset: "gadget",
  speaker: "gadget",
  bluetooth: "gadget",
  mic: "gadget",
  microphone: "gadget",
  kabel: "gadget",
  cable: "gadget",
  charger: "gadget",
  casan: "gadget",
  adaptor: "gadget",
  powerbank: "gadget",
  power_bank: "gadget",
  baterai: "gadget",
  casing: "gadget",
  case_hp: "gadget",
  softcase: "gadget",
  hardcase: "gadget",
  tempered_glass: "gadget",
  anti_gores: "gadget",
  tripod: "gadget",
  ringlight: "gadget",
  kamera: "gadget",
  camera: "gadget",
  webcam: "gadget",
  flashdisk: "gadget",
  usb: "gadget",
  memory_card: "gadget",
  sd_card: "gadget",
  hub: "gadget",
  dongle: "gadget",
  smartwatch: "gadget",
  smart_watch: "gadget",
  fitband: "gadget",
  jam_tangan: "gadget",

  // === RUMAH TANGGA & PERLENGKAPAN KOS ===
  rumah: "rumah-tangga",
  dapur: "rumah-tangga",
  kamar: "rumah-tangga",
  kos: "rumah-tangga",
  kosan: "rumah-tangga",
  kost: "rumah-tangga",
  home: "rumah-tangga",
  dekorasi: "rumah-tangga",
  decor: "rumah-tangga",
  estetik: "rumah-tangga",
  aesthetic: "rumah-tangga",
  perabotan: "rumah-tangga",
  furnitur: "rumah-tangga",
  furniture: "rumah-tangga",
  meja: "rumah-tangga",
  table: "rumah-tangga",
  kursi: "rumah-tangga",
  chair: "rumah-tangga",
  lemari: "rumah-tangga",
  rak: "rumah-tangga",
  organizer: "rumah-tangga",
  kotak_penyimpanan: "rumah-tangga",
  kasur: "rumah-tangga",
  bantal: "rumah-tangga",
  guling: "rumah-tangga",
  sprei: "rumah-tangga",
  selimut: "rumah-tangga",
  gordyn: "rumah-tangga",
  gorden: "rumah-tangga",
  tirai: "rumah-tangga",
  lampu: "rumah-tangga",
  light: "rumah-tangga",
  bohlam: "rumah-tangga",
  senter: "rumah-tangga",
  kipas: "rumah-tangga",
  fan: "rumah-tangga",
  ac_portable: "rumah-tangga",
  piring: "rumah-tangga",
  gelas: "rumah-tangga",
  mangkok: "rumah-tangga",
  sendok: "rumah-tangga",
  garpu: "rumah-tangga",
  wajan: "rumah-tangga",
  panci: "rumah-tangga",
  teflon: "rumah-tangga",
  pisau_dapur: "rumah-tangga",
  talenan: "rumah-tangga",
  botol_minum: "rumah-tangga",
  tumbler: "rumah-tangga",
  kotak_makan: "rumah-tangga",
  rice_cooker: "rumah-tangga",
  magic_com: "rumah-tangga",
  blender: "rumah-tangga",
  toaster: "rumah-tangga",
  oven: "rumah-tangga",
  dispenser: "rumah-tangga",
  tempat_sampah: "rumah-tangga",
  sapu: "rumah-tangga",
  pel: "rumah-tangga",
  kemoceng: "rumah-tangga",
  detergen: "rumah-tangga",
  pewangi_ruangan: "rumah-tangga",
  gantungan_baju: "rumah-tangga",
  hanger: "rumah-tangga",
  jemuran: "rumah-tangga",
  keset: "rumah-tangga",
  handuk: "rumah-tangga",
  cermin: "rumah-tangga",
  kaca: "rumah-tangga",

  // === BUKU & ALAT TULIS ===
  buku: "buku",
  novel: "buku",
  komik: "buku",
  manga: "buku",
  majalah: "buku",
  book: "buku",
  books: "buku",
  tulis: "buku",
  stationery: "buku",
  pensil: "buku",
  pulpen: "buku",
  pen: "buku",
  notebook: "buku",
  catatan: "buku",
  binder: "buku",
  kertas: "buku",
  diary: "buku",
  kamus: "buku",

  // === TAS SELEMPANG ===
  tas_selempang: "tas-selempang",
  slingbag: "tas-selempang",
  sling_bag: "tas-selempang",
  selempang: "tas-selempang",
  waistbag: "tas-selempang",
  waist_bag: "tas-selempang",
  clutch: "tas-selempang",
  totebag: "tas-selempang",
  tote_bag: "tas-selempang",
  pouch: "tas-selempang",
  shoulderbag: "tas-selempang",
  shoulder_bag: "tas-selempang",

  // === TAS GENDONG ===
  tas_gendong: "tas-gendong",
  ransel: "tas-gendong",
  backpack: "tas-gendong",
  carrier: "tas-gendong",
  tas_punggung: "tas-gendong",
  tas_sekolah: "tas-gendong",
  daypack: "tas-gendong",
  back_pack: "tas-gendong",
};

export function expandCategoryFromQuery(query: string): string | null {
  const q = query.trim().toLowerCase();
  
  // 1. Cek kecocokan langsung secara penuh
  if (CATEGORY_SYNONYMS[q]) {
    return CATEGORY_SYNONYMS[q];
  }
  
  // 2. Cek kecocokan parsial (misal: mencari "kaos hitam" akan mencocokkan sinonim "kaos")
  const words = q.split(/\s+/);
  for (const word of words) {
    if (CATEGORY_SYNONYMS[word]) {
      return CATEGORY_SYNONYMS[word];
    }
  }
  
  return null;
}
